# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_auto_20171122_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='inventory_number',
            field=models.IntegerField(verbose_name='Инвентарный номер:'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен:'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.TextField(max_length=300, verbose_name='Оборудование:'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default=None, max_length=254, verbose_name='Email сотрудника:'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name_employee',
            field=models.CharField(max_length=300, verbose_name='Имя Фамилия сотрудника:'),
        ),
    ]
