# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_auto_20171122_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='Сотрудник',
            new_name='Сотрудник:',
        ),
    ]
