# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0005_auto_20171122_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Сотрудник:',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.Users'),
        ),
    ]
