# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0006_auto_20171123_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='Сотрудник:',
            field=models.ForeignKey(blank=True, default='Склад', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.Users'),
        ),
    ]
