# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0007_auto_20171123_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Employees',
        ),
    ]
