# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0008_auto_20171123_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='name_employee',
            new_name='name',
        ),
    ]
