# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0011_auto_20171123_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='Сотрудник:',
            new_name='user',
        ),
    ]
