# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0012_auto_20171124_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email сотрудника:'),
        ),
    ]
