# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0013_auto_20171128_1009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип оборудования',
                'verbose_name_plural': 'Типы оборудования',
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='is_license',
            field=models.BooleanField(default=True, verbose_name='Лицензия'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='list_software',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Список ПО'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory_app.Type'),
        ),
    ]
